### ISSUE TITLE
Doors spawned by the map become wireable after loading a save

### ISSUE THREAD

**Issue by WolfeStrider** [robotboy655/gmod-hl2-tools#2]
If you have Wiremod enabled while Half-Life 2 Tools is also enabled doors spawned by the map will become wireable after loading a save on that map.

https://www.youtube.com/watch?v=ssD3oUL01dU

**Comment by robotboy655** [comment]
Is that a bad thing?

**Comment by WolfeStrider** [comment]
I mean if a door that's spawned by the map isn't wireable before saving then it's likely unintended for it to be wireable after the save unless that was your intention.
